image: gitpod/workspace-full

tasks:
  - name: Terminal
  - name: Docker
    init: make build && docker-compose up --no-start --build
    command: make up
    openMode: split-right
    
ports:
  - port: 4312
    onOpen: ignore
  - port: 7755
    onOpen: open-preview
  - port: 8055
    onOpen: ignore
  - port: 5530
    onOpen: ignore
