image: gitpod/workspace-full

tasks:
  - name: Terminal
  - name: Docker
    before: |
      export LARAVEL_URL=$(gp url 8055)
    init: make build && docker-compose up --no-start --build
    command: make up
    openMode: split-right
    
ports:
  - port: 4312 # MySQL
    onOpen: ignore
  - port: 5530 # private-api: Nest.js
    onOpen: ignore
  - port: 7755 # public-api: Laravel
    onOpen: open-preview
  - port: 8055 # web-ui: React
    onOpen: ignore
    visibility: public
